---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    channel: "eslint-3"
  fixme:
    enabled: true
ratings:
  paths:
  - "src/**.js"
  - "src/**.jsx"
exclude_paths:
- "**.test.js"
- "**/tools/"
