// flow-typed signature: 82f8afcc3cb08566704e871beb7994b2
// flow-typed version: <<STUB>>/graphql-typings_v0.0.1-beta-2/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-typings'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-typings' {
  declare module.exports: any;
}
