// flow-typed signature: f2a74a2332665a208b0ecbf4f3b9a1d7
// flow-typed version: <<STUB>>/wait-for-port_v0.0.2/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wait-for-port'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'wait-for-port' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wait-for-port/test/all' {
  declare module.exports: any;
}

declare module 'wait-for-port/test/helpers' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wait-for-port/index' {
  declare module.exports: $Exports<'wait-for-port'>;
}
declare module 'wait-for-port/index.js' {
  declare module.exports: $Exports<'wait-for-port'>;
}
declare module 'wait-for-port/test/all.js' {
  declare module.exports: $Exports<'wait-for-port/test/all'>;
}
declare module 'wait-for-port/test/helpers.js' {
  declare module.exports: $Exports<'wait-for-port/test/helpers'>;
}
