// flow-typed signature: 36d43c4e7d07979720dc188ec45dabee
// flow-typed version: <<STUB>>/wdio-firefox-profile-service_v0.0.1/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wdio-firefox-profile-service'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'wdio-firefox-profile-service' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wdio-firefox-profile-service/build/firefox-profile-launch-service' {
  declare module.exports: any;
}

declare module 'wdio-firefox-profile-service/gruntfile' {
  declare module.exports: any;
}

declare module 'wdio-firefox-profile-service/launcher' {
  declare module.exports: any;
}

declare module 'wdio-firefox-profile-service/test/extension/content/browserOverlay' {
  declare module.exports: any;
}

declare module 'wdio-firefox-profile-service/test/test.spec' {
  declare module.exports: any;
}

declare module 'wdio-firefox-profile-service/test/wdio.conf' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wdio-firefox-profile-service/build/firefox-profile-launch-service.js' {
  declare module.exports: $Exports<'wdio-firefox-profile-service/build/firefox-profile-launch-service'>;
}
declare module 'wdio-firefox-profile-service/gruntfile.js' {
  declare module.exports: $Exports<'wdio-firefox-profile-service/gruntfile'>;
}
declare module 'wdio-firefox-profile-service/index' {
  declare module.exports: $Exports<'wdio-firefox-profile-service'>;
}
declare module 'wdio-firefox-profile-service/index.js' {
  declare module.exports: $Exports<'wdio-firefox-profile-service'>;
}
declare module 'wdio-firefox-profile-service/launcher.js' {
  declare module.exports: $Exports<'wdio-firefox-profile-service/launcher'>;
}
declare module 'wdio-firefox-profile-service/test/extension/content/browserOverlay.js' {
  declare module.exports: $Exports<'wdio-firefox-profile-service/test/extension/content/browserOverlay'>;
}
declare module 'wdio-firefox-profile-service/test/test.spec.js' {
  declare module.exports: $Exports<'wdio-firefox-profile-service/test/test.spec'>;
}
declare module 'wdio-firefox-profile-service/test/wdio.conf.js' {
  declare module.exports: $Exports<'wdio-firefox-profile-service/test/wdio.conf'>;
}
